## @section Global parameters
## Global Docker image parameters
## Please, note that this will override the image parameters, including dependencies, configured to use the global value
## Current available global Docker image parameters: imageRegistry, imagePullSecrets

## @param global.imageRegistry Global Docker registry
## @param global.imagePullSecrets Global Docker registry secret names as an array
##
global:
  imageRegistry: ""
  # Specify secret with token
  # imagePullSecrets:
  #   - name: token1
  #   - name: token2
  imagePullSecrets: []

## @param replicaCount Number of replicas to deploy. Use an odd number.
##
replicaCount: 1

## @section Common parameters
## @param nameOverride String to partially override fullname template (will maintain the release name)
##
nameOverride: ""
## @param fullnameOverride String to fully override fullname template
##
fullnameOverride: ""
## @param namespaceOverride String to fully override the default namespace
##
namespaceOverride: ""

## Image configuration
##
image:
  ## @param image.registry Multitool image registry
  ##
  registry: ""
  ## @param image.repository Multitool image repository
  ##
  repository: praqma/network-multitool
  ## @param image.pullPolicy Multitool image pull policy
  ##
  pullPolicy: Always
  ## @param image.digest Multitool image digest, overrides image tag
  ##
  digest: ""
  ## @param image.tag Multitool image tag
  ##
  tag: "extra"
  ## @param image.pullSecrets Specify docker-registry secret names as an array
  ## pullSecrets:
  #   - name: token1
  #   - name: token2
  ##
  pullSecrets: []

## @param extraEnvVars Array containing extra env vars to configure Multiool
## For example:
## extraEnvVars:
##  ENV_VARIABLE: ""
##
extraEnvVars: {}

## Role Based Access Control
## ref: https://kubernetes.io/docs/admin/authorization/rbac/
##
service:
  ## @param service.hostNetwork Use Host network
  ##
  hostNetwork: true
  ## @param service.httpPort Container Port for HTTP
  ##
  httpPort: 1180
  ## @param service.httpsPort Container Port for HTTPS
  ##
  httpsPort: 11443

## ServiceAccount configuration
## ref: https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/
##
serviceAccount:
  ## @param serviceAccount.create Enable creation of ServiceAccount for Aiready pods
  ##
  create: false
  ## @param serviceAccount.annotations Additional custom annotations for the ServiceAccount
  ##
  annotations: {}
  ## @param serviceAccount.name The name of the ServiceAccount to use.
  ## If not set and create is true, a name is generated using the kanban.fullname template
  ##
  name: ""

## @param podAnnotations Additional pod annotations
## ref: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
##
podAnnotations: {}

## K8s Security Context
## https://kubernetes.io/docs/tasks/configure-pod-container/security-context/
## @param podSecurityContext Enable Pod Security Context
##
podSecurityContext: {}

## Container Security Context
## https://kubernetes.io/docs/tasks/configure-pod-container/security-context/
## @param securityContext Enable container security context
##
securityContext: {}

resources:
  ## Limits for the pod
  ##
  limits:
    ## @param resources.limits.cpu CPU limit for the pod
    ##
    cpu: '10m'
    ## @param resources.limits.memory Memory limit for the pod
    ##
    memory: 20Mi
  ## Requests for the pod
  ##
  requests:
    ## @param resources.requests.cpu CPU request limit for the pod
    ##
    cpu: '1m'
    ## @param resources.requests.memory Memory request limit for the pod
    ##
    memory: 20Mi

## @param nodeSelector Node labels for pod assignment
## Ref: https://kubernetes.io/docs/user-guide/node-selection/
##
nodeSelector: {}

## @param tolerations Tolerations for pod assignment
## Ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
##
tolerations: {}

## @param affinity Affinity for pod assignment
## Ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
## Note: podAffinityPreset, podAntiAffinityPreset, and  nodeAffinityPreset will be ignored when it's set
##
affinity: {}
